<?php
return [
  [
    'title' => '内容',
    'icon' => 'aicon ai-shezhi',
    'module' => 'mycms',
    'url' => 'mycms',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 0,
    'nav' => 1,
    'sort' => 100,
    'childs' => [
      [
        'title' => '内容管理',
        'icon' => 'typcn typcn-social-github',
        'module' => 'mycms',
        'url' => 'mycms/index/index',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 1,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '模型管理',
            'icon' => 'aicon ai-shujukuguanli',
            'module' => 'mycms',
            'url' => 'mycms/mymodel/modelList',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '表单管理',
            'icon' => 'typcn typcn-clipboard',
            'module' => 'mycms',
            'url' => 'mycms/Myform/formList',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '代码管理',
            'icon' => 'typcn typcn-sort-alphabetically',
            'module' => 'mycms',
            'url' => 'mycms/Element/Menu',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '测试用',
            'icon' => 'typcn typcn-chart-line-outline',
            'module' => 'system',
            'url' => 'mycms/test/form',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '字段类型管理',
            'icon' => 'typcn typcn-lightbulb',
            'module' => 'system',
            'url' => 'mycms/FieldType/fieldList',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '表格管理',
            'icon' => 'typcn typcn-th-small-outline',
            'module' => 'system',
            'url' => 'mycms/table/tablelist',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
    ],
  ],
];
